# ===== Application =====
spring.application.name=ztvis-backend
server.port=8080

# ===== DataSource =====
spring.datasource.url=jdbc:postgresql://localhost:5432/ztvis_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=ztvis_user
spring.datasource.password=ztvis_pass

# ===== JPA / Hibernate =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Flyway =====
spring.flyway.enabled=false

# ===== JWT =====
app.jwt.secret=ZeroTrustVisitorIdentityPlatformSuperSecretKey256BitsLong!!
app.jwt.expiration-ms=86400000

# ===== Logging =====
logging.level.com.ztvis=DEBUG
logging.level.org.springframework.security=INFO
